import keyMirror from 'key-mirror';

const ACTION_TYPES = keyMirror({
    FETCH_EXPERIMENTS: null,
    FETCH_EXPERIMENTS_SUCCESS: null,
    FETCH_VOLTAMOGRAMMS: null,
    FETCH_VOLTAMOGRAMMS_SUCCESS: null,
    ADD_EXPERIMENT: null,
    ADD_VOLTAMOGRAMM: null,
    SELECT_EXPERIMENT: null,
    SET_ERROR: null,
    ADD_SCAN: null,
    OPEN_ADD_VOLTAMOGRAMM: null,
    OPEN_ADD_SCAN: null,
    FETCH_SINGLE_VOLTAMOGRAMM: null,
    FETCH_SINGLE_VOLTAMOGRAMM_SUCCESS: null,
    FETCH_SINGLE_SCAN: null,
    FETCH_SINGLE_SCAN_SUCCESS: null,
    FETCH_SINGLE_MEASURE: null,
    FETCH_SINGLE_MEASURE_SUCCESS: null,
    SELECT_SCAN: null,
    LOGIN: null,
    UPDATE_EXPERIMENT: null,
    UPDATE_VOLTAMOGRAMM: null
});

export default ACTION_TYPES;